### ISSUE TITLE
djangorestframework no longer implements request.QUERY_PARAMS

### ISSUE THREAD

**Issue by baxrob** [jpadilla/django-rest-framework-jsonp#6]
Django error:
NotImplementedError at /json-filtered-result
`request.QUERY_PARAMS` has been deprecated in favor of `request.query_params` since version 3.0, and has been fully removed as of version 3.2.

Updating line 26 in renderers.py fixes the issue

**Comment by jpadilla** [comment]
@baxrob a PR with a compat fix is welcome :)

**Comment by subsetpark** [comment]
Hey @jpadilla, I've got a PR open with passing tests: https://github.com/jpadilla/django-rest-framework-jsonp/pull/8

**Comment by jpadilla** [comment]
Should be fixed in master branch now. Thanks!
